### PR TITLE
Update dependencies for Go1.18 compatibility

### LINKED ISSUE #757: Panic on sealing when built with Go 1.18
**Which component**:
kubeseal

**Describe the bug**
panic with Go 1.18 RC1. Tested working with Go 1.17.3

**Version of Kubernetes**:

```
$ kubectl --context do-nyc1-ua-utility-cluster version                                   
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:45:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Repro:**

Input file:
```
apiVersion: v1
data:
  dsn: aGVsbG8K
kind: Secret
metadata:
  name: crdb-dsn
  namespace: default
type: Opaque
```

Run this command and get the crash

```
$ cat secrets.yml | kubeseal --context do-nyc1-ua-utility-cluster --format yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4113bc]

goroutine 1 [running]:
reflect.mapiternext(0xc00020cbd0?)
        /home/h32/.gvm/gos/go1.18rc1/src/runtime/map.go:1378 +0x19
github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x7f91b0fcd108?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:136 +0x32
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0003f5d40, 0xc000348338, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:297 +0x31a
github.com/json-iterator/go.(*placeholderEncoder).Encode(0x10a7680?, 0xc000362d01?, 0xc00016a378?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:332 +0x22
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000319950, 0x10849d4?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc00035a030, 0x415501?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00035bf50, 0xff8b5c?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x56
github.com/json-iterator/go.(*structEncoder).Encode(0xc00037c090, 0x0?, 0xc00016a360)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x765
github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0001da960?, 0x0?, 0x0?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_optional.go:70 +0xa4
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0004c1410, 0xc000348280, 0xc0003f5590?)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:219 +0x82
github.com/json-iterator/go.(*Stream).WriteVal(0xc00016a360, {0x11b36a0, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x158
github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0001da960, {0x11b36a0, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0xc9
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xfde437?, {0x1393d68?, 0xc000348280?}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00003caa0, {0x1393d68, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0001501e0, {0x1393d68?, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0001501e0, {0x1393d68, 0xc000348280}, {0x1390e60, 0xc0003f5530})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/apimachinery/pkg/runtime.Encode({0x7f91882c7f38, 0xc0001501e0}, {0x1393d68, 0xc000348280})
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/runtime/codec.go:50 +0x64
main.resourceOutput({0x1392460, 0xc000010018}, {0xc0001ea0e0, {0x1391d60, 0xc00000eb70}, {0xc0001ce600, 0x3, 0x4}, {0x13a2108, 0xc00003ca00}}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:411 +0x125
main.sealedSecretOutput(...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:421
main.seal({0x1392440, 0xc000010010}, {0x1392460, 0xc000010018}, {0xc0001ea0e0, {0x1391d60, 0xc00000eb70}, {0xc0001ce600, 0x3, 0x4}, ...}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:302 +0x674
main.run({0x13a2b00, 0xc000040098}, {0x1392460?, 0xc000010018}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:741 +0xc4e
main.main()
        /home/h32/.gvm/pkgsets/go1.18rc1/global/pkg/mod/github.com/bitnami-labs/sealed-secrets@v0.17.3/cmd/kubeseal/main.go:748 +0x33b
```

Ran on linux/amd64

### PR DESCRIPTION
**Pull request by Hades32**
Just updates dependencies that are broken in Go 1.18. Fixes #757

### CODE REVIEW

**Review by mkmik — COMMENTED** [review]
Thank you; keeping the k8s dependencies up to date is a good idea even without the go1.18 issue;

the tests fail though

**Comment by Hades32** [comment]
Seems I missed to push additional dependency updates. Should be fixed now

**Review by mkmik — APPROVED** [review]
Thanks!

**Review by juan131 — APPROVED** [review]
LGTM!

NOTE: We're currently supporting & testing in the CI Go `1.16` and 1.17 (and it'll continue like this while 1.18 isn't considered stable). Therefore, we can't promise that we'll break compatibility with 1.18 again in the future.

**Review by alvneiayu — APPROVED** [review]
LGTM

**Pull request merged**
