### PR TITLE
initial import from stable repo

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

---
This change is [Reviewable](https://reviewable.io/reviews/bitnami-labs/sealed-secrets/484)

### CODE REVIEW

**Review by mkmik — APPROVED** [review]

**Comment by mkmik** [comment]
Will merge once chart linter us happy

**Comment by davidkarlsen** [comment]
@mkmik Please see https://github.com/bitnami-labs/sealed-secrets/issues/389#issuecomment-740566425

**Comment by mkmik** [comment]
Perhaps it's better to just migrate it here without any change and disable the linter for now until we upgrade the CRD?

**Comment by davidkarlsen** [comment]
sgtm.
It passes now.
Do you want to sign the charts or not and I can clean up that?
Also - you might want to tune the trigger for chart-release job since you have a mono-ish repo.

**Comment by fliphess** [comment]
@davidkarlsen Did you import the history from the stable chart?

**Comment by davidkarlsen** [comment]
@fliphess yes, this is https://github.com/helm/charts/tree/master/stable/sealed-secrets - the deprecation + CI

**Comment by mkmik** [comment]
Is this ready to be merged?

**Comment by davidkarlsen** [comment]
@mkmik It would be good if you could respond to https://github.com/bitnami-labs/sealed-secrets/pull/484#issuecomment-741052496 and the last polishing can be done.

**Comment by mkmik** [comment]
@davidkarlsen Thank you so much for helping out! will merge as soon as the CI is happy

**Comment by davidkarlsen** [comment]
squash it so we get a nice history, the rest can be found in the PR anyways.

**Pull request merged**
