### PR TITLE
Add CRD schema and fix JSON errors

### LINKED ISSUE #82: Add/restore openapi schema for CRD
See discussion during PR #73.  We had to remove the schema due to upstream k8s limitations that left us with no option to keep the schema _and_ allow an object with arbitrary keys.  This issue is to track finding a workaround and/or upstream fix that allows us to have key/value objects _and_ a CRD schema.

### PR DESCRIPTION
**Pull request by snorwin**
The lack of proper schema validation can lead to errors when using libraries that rely on K8s API responses (JSON) to match Go structs. In particular, if there are errors in the unmarshaling  a  SealedSecret resource, the controller will stop watching and processing all the resources of that kind. To avoid such problems, an OpenAPI scheme was introduced wherever possible. 

**Description of the change**
- OpenAPI schema generation using controller-gen
- preserve unknown fields only for `.spec.encryptedData`
- ignore errors when unmarshaling `.spec.encryptedData` as the structure isn't ensured by any schema

**Benefits**
- controller still valid processes sealed secrets even if there are any invalid ones
- OpenAPI schema guides the user to create SealedSecret and prevents structural errors

**Possible drawbacks**
None.

**Applicable issues**
Fixes #82 #505

### CODE REVIEW

**Comment by mkmik** [comment]
awesome I was meaning to do this since forever but I was lazy; thank you!

**Comment by mkmik** [comment]
Unfortunately I can no longer approve the workflows :-(

**Comment by snorwin** [comment]
As we now enable validation maybe it would make sense to set `Data`  in `.spec.template` as optional too, what are you thinking?
```
	// Keys that should be templated using decrypted data
	// +optional
	Data map[string]string json:"data"
```

**Comment by mkmik** [comment]
yeah making that optional seems reasonable

**Comment by josvazg** [comment]
Hi @snorwin, thanks for this fix

I will review on our side and we can hopefully have it merged soon

**Review by josvazg — APPROVED** [review]
LGTM!

Thanks a lot for this contribution!

**Comment by stefancoetzee-xneelo** [comment]
Shouldn't we have updated the patch version as we're touching the schema?

**Pull request merged**
