### PR TITLE
Bump the Golang project version to 1.17

### PR DESCRIPTION
**Pull request by alvneiayu**
**Description of the change**

The [release building](https://github.com/bitnami-labs/sealed-secrets/runs/5693540845?check_suite_focus=true) is failing trying to compile the project using the Golang version 1.16.14. It seems that it is a problem related to the sigs.k8s.io/json.
```
Error: ../../../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
Error: ../../../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
This is a known issue on internet. It seems that sigs.k8s.io/json uses new code added in 1.17. 
The CI jobs that we are running when we receive a PR are not failing because the "^" in our CI yaml files are using the last Golang version cached (1.17.7/1.17.8).

Checking our actions, I saw that we did several test using the version 1.17.X. So at this point, I think that it is a really good idea to use a newer Golang version than the 1.16.

**Benefits**

Have releases and our CI compiling in 1.17.8. Compile in a newer Golang version.

### CODE REVIEW

**Review by agarcia-oss — APPROVED** [review]
A very much necessary change

**Comment by JeNeComprendPas** [comment]
Hi, we can notice that in 1.17 and 1.18 go get is deprecated for installing executables.
[https://go.dev/doc/go-get-install-deprecation#:~:text=Starting%20in%20Go%201.17%2C%20installing,the%20%2Dd%20flag%20were%20enabled.](documentation)

This is used in the line 96 of ci.yml : 
`(cd /tmp; GO111MODULE=on go get github.com/onsi/ginkgo/ginkgo@v1.14.2)`

**Comment by alvneiayu** [comment]
I was forced to set up the renameio version to v0.1.0. The version v1.0.1 [doesn't have Windows support](https://pkg.go.dev/github.com/google/renameio#section-readme). **This is a temporally fix**. Creating an issue to find a better solution to this problem.

**Review by alemorcuq — APPROVED** [review]
LGTM

**Review by agarcia-oss — APPROVED** [review]

**Review by mkmik — APPROVED** [review]

**Pull request merged**
