### PR TITLE
Travis: Update GO and Kubernetes Versions

### PR DESCRIPTION
**Pull request by kskewes**
Periodic update to current versions.

Go:
- 1.10 (since Feb 2018) - later versions not passing, haven't investigated yet.
- 1.9 (existing)

Kubernetes:
- Minikube 1.0.0
- Current releases

### CODE REVIEW

**Comment by kskewes** [comment]
Minikube changes for 1.12-1.14 sorted.

Integration test error on Go 1.11+ even against k8s 1.9. (Haven't tried Go 1.10)
```
# Assumes a k8s cluster exists, with controller already installed
ginkgo -p -tags 'integration' integration -- -kubeconfig /home/travis/.kube/config -kubeseal-bin /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/kubeseal -controller-bin /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/controller
Failed to compile integration:
# github.com/bitnami-labs/sealed-secrets/integration
vet: integration/kubeseal_test.go:230:6: c declared but not used
Ginkgo ran 1 suite in 28.290892054s
Test Suite Failed
Makefile:68: recipe for target 'integrationtest' failed
make: *** [integrationtest] Error 1
```

Will take another stab at this shortly, may or may not need `client-go` update.

**Comment by kskewes** [comment]
Didn't look very far at why Go 1.11 not passing. Perhaps another day (separate PR).

Ended up writing a `Vagrantfile` and supporting bootstrap script based off the Travis CI process so I can validate any changes locally.
Whilst it takes a while to run (YMMV wrt cpu/mem) it has been pretty useful.
https://github.com/kskewes/sealed-secrets/commit/01614bbe69531bc26d3b04cb9f6dc9291de768ff
Happy to PR the vagrant changes if you like Gus and maintain for the foreseeable future.
I realise it can be a pain to have two tools for the same job (Travis & Vagrant) though.

**Comment by mkmik** [comment]
Sorry, didn't notice this; I bumped the Go revision to 0.12 in #175 (and made `vet` happy; you had to run vet with `-tags integration` to make it find errors in the integration testing sources).

**Pull request merged**
