### PR TITLE
Add SealedSecret 'template' to use when constructing Secret

### LINKED ISSUE #72: Allow a user to know whether the controller actually unsealed a secret
Some users can create/read the sealedsecrets resource kind but they cannot list the secrets on the api server nor tail the logs of the sealed secrets controller (e.g. because of RBAC); it's currently impossible to know whether the secret has been successfully unsealed.

Possible ideas: events and/or a "status" section (like pods, deployments etc)

```
status:
  secret:
    created: True
```

(I was also wondering about the `condition` objects but it seems they might be going away https://github.com/kubernetes/kubernetes/issues/7856)

### LINKED ISSUE #92: Missing annotations & labels
When creating a new sealed-secret based on a existing secret.yaml labels and annotations are lost.

This is very important, as some labels and annotations are related to helm lifecycle.

### PR DESCRIPTION
**Pull request by mkmik**
Merge #129 into current codebase (which as diverged in the meantime)

```
This change adds a spec.template to the SealedSecrets schema, which
includes metadata and type used when constructing the new Secret.
(All the Secret fields other than data/encryptedData)

Also this change adds:

Events to the SealedSecret describing progress/errors while
unsealing.
A SealedSecret status structure that exposes overall
success/failure.
```

Fixes #92
Fixes #72

### CODE REVIEW

**Comment by atomatt** [comment]
bors r+

based on a very superficial review :crossed_fingers:

**Comment by mkmik** [comment]
bors delegate=atomatt

**Comment by bric3** [comment]
Could be labelled as 0.8.0 as well :)

**Comment by mkmik** [comment]
> Could be labelled as 0.8.0 as well :)

To avoid overcrowding the milestone "changelog" I tended to favour labelling tracking issues (such as #92 in this case) over PRs. My mind can easily be changed with arguments :-)

**Comment by bric3** [comment]
@mkmik I had the opposite practice as it allows to track which work get into which milestone, after several years I found it useful. But your point is just as fine it just address different concerns ;)

**Pull request merged**
