### PR TITLE
fix: remove trailing dashes for multidoc yaml

### LINKED ISSUE #1330: `kubeseal` appends extra document separator `---` when format is YAML
**Which component**:
kubeseal (v0.24.0)

**Describe the bug**
When sealing a secret with `kubeseal`, an extra [YAML document separator](https://yaml.org/spec/1.0/#id2561718) (`---`) is added to the output (since version `v0.24.0`). This causes YAML parsers to fail or parse an extra empty document.

**To Reproduce**

1. Create a simple secret file `secret.yml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  foo: bar
```
2. Run `kubeseal --format yaml --secret-file secret.yaml --cert cert.pem`

The resulting YAML document will contain an extra document separator at the end:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
[..]
spec:
  [..]
  template:
    [..]
    type: Opaque
---
```

**Expected behavior**
The resulting YAML document MAY contain a document separator **before** each document. The resulting YAML document MUST NOT contain a trailing document seperator.

**Additional context**
This was most likely caused by https://github.com/bitnami-labs/sealed-secrets/pull/1304 , specifically https://github.com/bitnami-labs/sealed-secrets/pull/1304/files#diff-92f00e9d744fba4dee224973d289d4a24568a3b50a98996622e5928e86dfca04R409 .

This could be solved by putting the document separator in front of every document (instead of the end).

### PR DESCRIPTION
**Pull request by theurichde**
Fixes #1330 #1296

**Description of the change**

While introducing multi document support for JSON and YAML, we introduced trailing dashes for YAMLs, which violates the YAML specification. This change will separate JSON and YAML with `\n` for JSON and `---` for YAML, only if there are multiple documents given. It will not append a new line or dashes for the last document

**Benefits**

YAML specification is met, linters will be happy.

**Possible drawbacks**

**Applicable issues**

- fixes #1330 #1296 

**Additional information**

### CODE REVIEW

**Comment by tewfik-ghariani** [comment]
Or maybe you could simply add the `---` at the beginning of every object for YAML format ^^

**Comment by theurichde** [comment]
> Or maybe you could simply add the `---` at the beginning of every object for YAML format ^^

Yeah, sure. That would be the more pragmatic way. I thought of having it clean from the beginning, with only a separator in between. But having just the dashes upfront every document, would be also fine for me.

What do you think @alemorcuq @agarcia-oss @alvneiayu ?

**Comment by lindhe** [comment]
Having `---` at the beginning of every YAML document is considered good practice by the the third party tool [yamllint](https://github.com/adrienverge/yamllint): https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

**Comment by theurichde** [comment]
Let's go the pragmatic way. There is also muuuch less code changes involved.

**Comment by theurichde** [comment]
I will close this PR in favor of #1335

**Pull request closed without merging**
