### PR TITLE
Add Nixpkgs to installation options in README.md

### PR DESCRIPTION
**Pull request by bergkvist**
[Nixpkgs](https://github.com/NixOS/nixpkgs) is a cross-platform package manager for macOS and Linux.

### CODE REVIEW

**Review by alemorcuq — CHANGES_REQUESTED** [review]
Thanks! I didn't know this was being published on Nixpkgs. However, I've noticed it's not up to date (current version is 0.17.0 while latest is 0.17.5). Could you add a disclaimer saying that the package is not maintained by us?

**Comment by bergkvist** [comment]
`nixpkgs.kubeseal` is now on the latest version (0.17.5) on `unstable` and `22.05` channels. See https://github.com/NixOS/nixpkgs/commit/e4e01fc34f4d0f07d13baf08fb7215151ac5fcdd

**Comment by alvneiayu** [comment]
hi @bergkvist 

And now we are in 0.18.0. Could you add a disclaimer just to notify to our users that they need to check the version used in nixpkgs, please? Just to notice in our README that maybe the version used in nixpkgs is not the latest one.

Thanks a lot again for your time and your PR

**Review by alvneiayu — APPROVED** [review]
LGTM

**Review by agarcia-oss — APPROVED** [review]

**Review by alemorcuq — APPROVED** [review]

**Review by alvneiayu — APPROVED** [review]

**Pull request merged**
