### PR TITLE
updated kube-libsonnet to v1.14.6

### PR DESCRIPTION
**Pull request by jbianquetti-nami**
upgraded with ```jb --jsonnetpkg-home="./vendor_jsonnet/" update```

### CODE REVIEW

**Review by mkmik — APPROVED** [review]

**Comment by jbianquetti-nami** [comment]
bors try

**Comment by mkmik** [comment]
bors try

**Comment by mkmik** [comment]
bors help

**Comment by jbianquetti-nami** [comment]
Error is: 

```
./kubeseal --kubeconfig /Users/bianquetti/.kube/config
(tty detected: expecting json/yaml k8s resource in stdin)
error: cannot fetch certificate: no endpoints available for service "http:sealed-secrets-controller:"
```

**Comment by mkmik** [comment]
This can mean many things; likely that the controller just doesn't start

**Comment by jbianquetti-nami** [comment]
I'm able to fetch the certificate from a pod running in the same NS with ```curl  -L 172.18.0.9:8080/v1/cert.pem```

But I'm not able to access by using the k8s proxy 

```
curl -k  -H "Authorization: Bearer $TOKEN"   -H "Accept: application/x-pem-file, */*" -H "User-Agent: kubeseal/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://172.17.0.2:8443/api/v1/namespaces/kube-system/services/http:sealed-secrets-controller:/proxy/v1/cert.pem'
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"http:sealed-secrets-controller:\"","reason":"ServiceUnavailable","code":503}
```

**Comment by mkmik** [comment]
Can you diff the yaml of the current release with the yaml produced by this PR?

**Pull request closed without merging**
