### PR TITLE
[WIP] Add SealedSecret 'template' to use when constructing Secret

### LINKED ISSUE #72: Allow a user to know whether the controller actually unsealed a secret
Some users can create/read the sealedsecrets resource kind but they cannot list the secrets on the api server nor tail the logs of the sealed secrets controller (e.g. because of RBAC); it's currently impossible to know whether the secret has been successfully unsealed.

Possible ideas: events and/or a "status" section (like pods, deployments etc)

```
status:
  secret:
    created: True
```

(I was also wondering about the `condition` objects but it seems they might be going away https://github.com/kubernetes/kubernetes/issues/7856)

### LINKED ISSUE #92: Missing annotations & labels
When creating a new sealed-secret based on a existing secret.yaml labels and annotations are lost.

This is very important, as some labels and annotations are related to helm lifecycle.

### PR DESCRIPTION
**Pull request by anguslees**
This change adds a `spec.template` to the SealedSecrets schema, which
includes `metadata` and `type` used when constructing the new Secret.
(All the Secret fields _other_ than `data`/`encryptedData`)

Also this change adds:
- Events to the SealedSecret describing progress/errors while
  unsealing.
- A SealedSecret `status` structure that exposes overall
  success/failure.

Fixes #92
Fixes #72

### CODE REVIEW

**Comment by glerchundi** [comment]
Hopefully this also fixes #86, thanks for taking the time to work on this @anguslees, keep up the good work!

**Comment by goober** [comment]
Looks promising, great work @anguslees!  Can I help out with anything to get this change ready for the main branch?

**Comment by yinzara** [comment]
I would also love to help if there is any way we can get this to work.  This PR is the only way to use the "kubernetes-replicator" to replicate secrets created by SealedSecret as they require an annotation on the Secret itself.

**Comment by stevenpall** [comment]
Yup, I'm also looking for a way to add an annotation to the resultant secret. @anguslees is there anything I/we can do to expedite getting this into master? Thanks!

**Comment by mkmik** [comment]
Moved to #180 in order to merge conflicts

**Pull request closed without merging**
