### PR TITLE
fix: fix typo and remove unused functions and constants

### PR DESCRIPTION
**Pull request by hezhizhen**
**Description of the change**

1. fix some typo
2. remove unused functions/methods/constants
3. explicitly handle some errors
4. reorder imports by goimports

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @hezhizhen 

There are too many changes different changes in this PR (Readme, functions and other things). Could you split this PR in one PR fixing the Readme and typos and keeping this one for the changes more focus in functional stuffs, please?.

Thanks a lot

Álvaro

**Review by alvneiayu — CHANGES_REQUESTED** [review]
hi @hezhizhen

There are too many changes different changes in this PR (Readme, functions and other things). Could you split this PR in one PR fixing the Readme and typos and keeping this one for the changes more focus in functional stuffs, please?.

Thanks a lot

Álvaro

**Comment by hezhizhen** [comment]
> hi @hezhizhen
> 
> There are too many changes different changes in this PR (Readme, functions and other things). Could you split this PR in one PR fixing the Readme and typos and keeping this one for the changes more focus in functional stuffs, please?.
> 
> Thanks a lot
> 
> Álvaro

Okay, I'll do it later.

**Comment by hezhizhen** [comment]
https://github.com/bitnami-labs/sealed-secrets/pull/750

**Comment by hezhizhen** [comment]
https://github.com/bitnami-labs/sealed-secrets/pull/751

**Comment by hezhizhen** [comment]
Hi @alvneiayu I just split this PR into 2s:

* #750 - fix typo and some grammar problems in README.md
* #751 - address some issues raised by golangci-lint (removing unused code and etc)

Please review those two PRs. Thx.

**Comment by juan131** [comment]
Closing this PR in favor of https://github.com/bitnami-labs/sealed-secrets/pull/750 and https://github.com/bitnami-labs/sealed-secrets/pull/751

**Pull request closed without merging**
