### PR TITLE
Publish sealed-secret-controller in Dockerhub

### PR DESCRIPTION
**Pull request by alvneiayu**
**Description of the change**

Publish the controller image in Dockerhub instead of Quay

### CODE REVIEW

**Review by agarcia-oss — APPROVED** [review]

**Comment by sathieu** [comment]
@alvneiayu @alemorcuq @agarcia-oss What is the reason for this change? docker hub has bandwith limits...

**Comment by xak2000** [comment]
Maybe this is the reason:

> On June 1 2022, Repository Signing and App Registry will be removed from quay.io. Users should migrate to use alternatives which are now natively supported (Cosign & Helm respectively)

Right now my k8s can't get the image from https://quay.io/bitnami/sealed-secrets-controller:v0.17.3

The page says:

> 403: Unauthorized
> You are not authorized to view this resource

**Comment by sathieu** [comment]
@xak2000 Yes. All images are now at [bitnami/sealed-secrets-controller](https://hub.docker.com/r/bitnami/sealed-secrets-controller/tags)

**Comment by egeland** [comment]
Were the images removed from quay by Bitnami? or is it a quay change that suddenly broke all older installs?

**Comment by reilly3000** [comment]
For reference: https://github.com/bitnami-labs/sealed-secrets/issues/822

**Pull request merged**
