### PR TITLE
Finishing Add SealedSecret 'template' to use when constructing Secret

### LINKED ISSUE #72: Allow a user to know whether the controller actually unsealed a secret
Some users can create/read the sealedsecrets resource kind but they cannot list the secrets on the api server nor tail the logs of the sealed secrets controller (e.g. because of RBAC); it's currently impossible to know whether the secret has been successfully unsealed.

Possible ideas: events and/or a "status" section (like pods, deployments etc)

```
status:
  secret:
    created: True
```

(I was also wondering about the `condition` objects but it seems they might be going away https://github.com/kubernetes/kubernetes/issues/7856)

### LINKED ISSUE #92: Missing annotations & labels
When creating a new sealed-secret based on a existing secret.yaml labels and annotations are lost.

This is very important, as some labels and annotations are related to helm lifecycle.

### PR DESCRIPTION
**Pull request by chrisharm**
Attempting to finish the work started by @anguslees in #129 

```
This change adds a spec.template to the SealedSecrets schema, which
includes metadata and type used when constructing the new Secret.
(All the Secret fields other than data/encryptedData)

Also this change adds:

Events to the SealedSecret describing progress/errors while
unsealing.
A SealedSecret status structure that exposes overall
success/failure.
```

Fixes #92
Fixes #72

### CODE REVIEW

**Comment by glerchundi** [comment]
This would also solve #86, right? Btw thanks to everyone for pushing this forward! /cc @mkmik

**Comment by chrisharm** [comment]
> This would also solve #86, right? Btw thanks to everyone for pushing this forward! /cc @mkmik

Yes, that's correct.  The following secret 
```
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: awesomeapps
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImMzUi4uLnpFMiJ9fX0= 
type: kubernetes.io/dockerconfigjson

```
would be sealed as follows:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myregistrykey
  namespace: awesomeapps
spec:
  encryptedData:
    .dockerconfigjson: AgAKRok+du/e7Zm+xtWJOPoAek/8TnLBtGbYphLTxz0qoOVatJ4EYXdwfqKkeE7pKw7olH+v1bGSs2kIlcihkxazdOXSGkZx5vXz6J0zUDnDyYaz7prsWHiOJ4eaXPkg9bcrh73AdoLX7Tb0wD4duYjGOvNJbuKSK848TlHZYv2J0BT3bgqj94z4ZWq0g2JSZmmBavnl+qUfRd9N/nPC6yS4E38WODZ1DqhUCAp7rK6U98GOWjG8IygGvAsSh0j8AHaSmgB6fO79l2G4BZk1NrEtnimo5wSzpIXI51x4m/w8heGDhjoJFaAAY2M26ve/3OnWDlw4z9w/qOGhmLcPIHEDmzKkGFCexrVUN94T7n1X6guFaJbx00WJxoKUw7zjch21i7TOpj1ijh++01LLrxAcXjPvp/kfVau9mM4ILK+PsFW/Ne2Niu55B8605UM+Z8QFFEn1uZR4wQMsYwWwu1bv8JKXXeX6RqpVyVCsG6fF7STFEsQqEExYZOimdJjULhox9G9OyNKOU+/ngeEti9MhV7XmZ7vcJJPWPEjwN41JEcid6Dt0fBTFp6Saq+1rpxRUR/k6tnwjFxhAvRjZ26g03FeQPkQy6ezFKO9uTMiWnW1GIeXpBWLZNxCa/fMfgAavTaAfpbe2wJNHutVI0Pu9eGZGN/tMdTfTKjqBaA9JHMlqcnYFN/Zer3gzIYUOQ2MIYOyn9R7g1Kxrkb0+YNkSqee05Mu9OduCG5WuYaBTZefdN1fZZJ60tHpLnah5SHOMjeo3EyiKedBzM9lyxjbT4A==
  template:
    metadata:
      creationTimestamp: null
      name: myregistrykey
      namespace: awesomeapps
    type: kubernetes.io/dockerconfigjson
status: {}

```
and should produce the same secret when unsealed.

**Comment by chrisharm** [comment]
Although it should produce the same secret... I'm actually getting an error in the controller 

```
2019/07/10 01:27:48 Updating awesomeapps/myregistrykey
2019/07/10 01:27:48 secret doesn't exist, will attempt to create one.
2019/07/10 01:27:48 Error updating awesomeapps/myregistrykey, will retry: Secret "myregistrykey" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable
```

**Comment by mkmik** [comment]
> Although it should produce the same secret... I'm actually getting an error in the controller
> 
> ```
> 2019/07/10 01:27:48 Updating awesomeapps/myregistrykey
> 2019/07/10 01:27:48 secret doesn't exist, will attempt to create one.
> 2019/07/10 01:27:48 Error updating awesomeapps/myregistrykey, will retry: Secret "myregistrykey" is invalid: type: Invalid value: "kubernetes.io/dockerconfigjson": field is immutable
> ```

The codebase diverged quite a bit; I merged and painstakingly resolved the conflicts in #180.

I tested your example here about docker config and it works in #180.

I'm going to extract your other contributions in another PR, since I tried to keep the merge as small as possible. Closing as duplicate of #180

**Pull request closed without merging**
