### PR TITLE
Fix endless loop when a single sealedsecret has a base64 decode error

### LINKED ISSUE #201: Endless loop in controller on invalid base64 encrypted data
It seems that improperly encoded base64 encryptedData causes an endless loop in the controller. For example:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: brokenss
spec:
  encryptedData:
    foo: foo1foo
    bar: bar1bar
```

As soon as this kind of broken sealed-secret is added, controller will log each second a new message like this:
```
E0725 15:10:11.704525       1 reflector.go:205] github.com/bitnami-labs/sealed-secrets/cmd/controller/controller.go:155: Failed to list *v1alpha1.SealedSecret: v1alpha1.SealedSecretList.Items: []v1alpha1.SealedSecret: v1alpha1.SealedSecret.Spec: v1alpha1.SealedSecretSpec.EncryptedData: decode base64: illegal base64 data at input byte 4, error found in #10 byte of ...|:"bar1bar","foo":"fo|..., bigger context ...|0000001"},"spec":{"encryptedData":{"bar":"bar1bar","foo":"foo1foo"}}},{"apiVersion":"bitnami.com/v1a|...
```

Unfortunately, this blocks the processing of any other sealed-secret added afterwards. The only way to break the loop is to delete the broken sealed-secret.

I tried looking in the code for a way to catch the base64-decoding error and consider the sealed-secret broken, as when the key doesn't match. But it seems this happens too deep in the call stack. The only way I found to "fix" the problem was to change the type of the `encryptedData` field in the `SealedSecretSpec struct` to `string` instead of `[]byte` so that we control the base64-decoding. You can find [here](https://github.com/bitnami-labs/sealed-secrets/compare/master...catac:fix-loop) the full set of changes for this.

Please let me know if this approach is ok for you and I'll be happy to adapt the code to your comments and come back with a PR. Or maybe you see a better approach?

Thanks!

### PR DESCRIPTION
**Pull request by mkmik**
Closes #201 

Supersedes #203, adding fixes to tests and addressing review comments (created new PR because I cannot add commits in that fork)

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @bakins, this appears to be a breaking change in the API, and yet the api version wasn't bumped?

We had a PR sent for OpenFaaS Cloud, but it wasn't tested properly by the author and has broken our pipeline now. We're trying to figure out what's wrong.

Would you mind taking a quick look and pointing us in the right direction? 

https://github.com/openfaas/openfaas-cloud/commit/0bd4c834fab25ec6a65a4f015a1271d00a81cbf1#diff-fa778be7508cf2401eb85fe1d5f4dece

We end up with a weird JSON value in the secret instead of a working pipeline.

If you had time, it would be most appreciated. Thank you.

**Comment by mkmik** [comment]
were you using sealed-secrets as a library?

**Comment by alexellis** [comment]
We are using your clientset in order to import SealedSecrets from a CI pipeline.

**Comment by mkmik** [comment]
sorry about the breaking change then; I didn't know. We're focusing on not breaking wire format compatibility for end users interacting with k8s manifests in the normal way.

I'll keep it in mind that we have direct dependencies to the pkg

**Comment by mkmik** [comment]
I think we could find an alternative way to deal with base64 encoding error handling. how bad is this breakage for you?

**Comment by alexellis** [comment]
Very bad, but it looks like I've got it back to a working state now in the linked PR over on our repo.

I also saw a mention that "data" will be deprecated/go-away, is there any issue that we could track for that? Thank you for responding so quickly.

**Comment by mkmik** [comment]
> I also saw a mention that "data" will be deprecated/go-away, is there any issue that we could track for that?

No; and I'm taking this very slowly; there are still tons of users on <=0.7, so this thing is not going away any time  soon (possibly ever)

**Pull request merged**
