### PR TITLE
Fix issue where sealed secrets status is not updated if sealed secret…

### LINKED ISSUE #853: Status shows `no key could decrypt secret` for successful created secret
**Which component**:
kubeseal: v0.17.4
sealed-secret-controller: v0.17.5
kubernetes: 1.22.6

**Describe the bug**
The `status` feature, where you can see if the creation of a secret through the controller was successful or not is partly not correct. In this case the status says `message: no key could decrypt secret (<key>)` but the `logs` and `events` of the controller says `SealedSecret unsealed successfully`.

Screen Shot 2022-06-01 at 18 38 26

**To Reproduce**
- upgrade the controller from v0.12.4 to v0.17.5
- Restart the pod
- compare `status` and `controller log` or `events` entries

**Expected behavior**
When the creation was successful the `status` should show `SealedSecret unsealed successfully` like the logs and the `events`.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

**Additional context**
I am not sure if i misunderstood the `status` feature 🤔.

### PR DESCRIPTION
**Pull request by mowirth**
**Description of the change**

Removes a check used to prevent unnecessary updates of the sealed secrets status.

**Benefits**

The check is used to prevent unnecessary updates on the sealed secrets status. 

However, in some cases, the sealed secret might not be updated to successfully generate the secret.
For example, if a secret is managed by a different controller, the generation from a sealedSecret would fail; if the controller is removed later, the secret would be unsealed successfully.
In this case, the check prevents a successful update leading to issues when the secret is successfully unsealed (and the successful unseal is reported), but the secret status is not updated since the generation/observedGeneration steps were not updated.

This is also an issue when using management tools such as ArgoCD, since the status would always report an error, while the secret is successfully unsealed.

**Possible drawbacks**

May increase updates of sealed secrets status if not necessary.

**Applicable issues**

- fixes #853 

**Additional information**

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @mowirth, 
First of all, thanks a lot for your PR.

I have some concerns about this solution because these lines that you are deleting will generate other issue already fixed in the past and also we are going to increase the CPU a lot (https://github.com/bitnami-labs/sealed-secrets/issues/223).

In my opinion, we need to find an alternative way to solve this problem.

Thanks a lot again

Álvaro

**Comment by mowirth** [comment]
Hi @alvneiayu ,

I added a check to only send an update if the status was changed - this way, a status change is still propagated, but only when necessary. 

Best regards and thanks,
Moritz

**Comment by alvneiayu** [comment]
hi @mowirth 

thanks a lot for the new modifications. I am testing it, I will come back ASAP with some feedback.

Álvaro

**Comment by alvneiayu** [comment]
hi @mowirth 

I tested it and it seems that the performance is OK. We have several tests included inside the controller_test.go file to check the Status. Could you take a look if it is possible to include a new test to be sure that future changes (new PRs from other issues) will not generate the same issue resolved?

Thanks a lot again for your PR

Álvaro

**Comment by mowirth** [comment]
@alvneiayu I added some tests to check whether the expected behaviour regarding the update is applied and that an errorneous update with a previously successfully unsealed sealed secret properly updates the condition.

**Review by alvneiayu — APPROVED** [review]
LGTM, and thanks a lot @mowirth for your awesome contribution

**Pull request merged**
