### PR TITLE
Use go modules without vendoring

### PR DESCRIPTION
**Pull request by mkmik**
Go modules are mature now and we don't need vendoring anymore

### CODE REVIEW

**Comment by alvneiayu** [comment]
hi @mkmik 

I think that it is a really awesome idea. The compilation is failing. I think that we need to do some changes to compile without the -mod vendor

Thanks

Álvaro

**Comment by mkmik** [comment]
I grepped quickly in .github but I didn't find mention of the mod vendor option; probably I grepped badly

**Comment by alvneiayu** [comment]
I think that the problem is in the Makefile. We have a GO_FLAG adding -mod=vendor and I think that we need to remove it.

**Comment by mkmik** [comment]
Fixed

**Review by alvneiayu — APPROVED** [review]
LGTM

**Pull request merged**
