### PR TITLE
Add labels to rbac, deployment and service

### PR DESCRIPTION
**Pull request by hamza3202**
This PR adds option to specify additional labels for deployment, service and RBAC resources

### CODE REVIEW

**Comment by hamza3202** [comment]
@mkmik Can I get a review on this please?

**Comment by hamza3202** [comment]
I am not sure why lint is failing. Happy to make any changes you suggest @mkmik

**Comment by mkmik** [comment]
it's not clear to me why the linter fails; works locally

**Comment by mkmik** [comment]
anybody can fix the pipeline; GH actions can be run in forks, so anybody can jump in to help this

**Comment by mkmik** [comment]
just curious: what is your use case? are you using a private mirror of the sealed-secrets image? Are you running in an air-gapped environment?

**Comment by mkmik** [comment]
> just curious: what is your use case? are you using a private mirror of the sealed-secrets image? Are you running in an air-gapped environment?

@hamza3202 uh sorry, confused you for #548; please ignore the question

**Comment by mkmik** [comment]
@hamza3202 anyway, I landed #550 with a possible fix can you please try to rebase and see if it still fails?

**Comment by hamza3202** [comment]
@mkmik I have done rebase, now other stages are passing but lint is still failing. The error is a bit strange
```
2021/03/10 09:04:53 Helm chart version: got: "1.15.0-r1", want: "1.15.0-r2"
```
as I have changed the chart version to `1.15.0-r2`

**Comment by mkmik** [comment]
Ah if it's only due to the version then it's fine.

Please don't bump the version. We handle releases independently from chart feature changes

**Comment by hamza3202** [comment]
@mkmik Done

**Comment by mkmik** [comment]
ok, perhaps #551 will fix that

**Comment by mkmik** [comment]
@hamza3202 please try rebasing again

**Comment by hamza3202** [comment]
@mkmik Seems to work now

**Comment by hamza3202** [comment]
@mkmik when can I expect to get this released?

**Comment by mkmik** [comment]
tomorrow

**Comment by hamza3202** [comment]
@mkmik the helm chart is still not released :-) I hope you can find some time to get it done :-)

**Comment by mkmik** [comment]
released now :-)

**Comment by hamza3202** [comment]
Thanks! It works as expected.

**Pull request merged**
