### PR TITLE
feat: multidoc support for yaml and json

### LINKED ISSUE #114: When sealing multiple secrets in singe yaml file only first is sealed
Steps to reproduce

```
10:27:56 in ~/Downloads/kubeseal-test
➜ kubectl create secret generic mysecret --dry-run --from-literal=foo=bar -o yaml >mysecret.yaml

10:28:13 in ~/Downloads/kubeseal-test
➜ cat mysecret.yaml                                                                             
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret

10:28:14 in ~/Downloads/kubeseal-test
➜ echo "---" >> mysecret.yaml

10:28:34 in ~/Downloads/kubeseal-test
➜ kubectl create secret generic mysecret2 --dry-run --from-literal=foo2=bar2 -o yaml >>mysecret.yaml

10:28:56 in ~/Downloads/kubeseal-test
➜ cat mysecret.yaml                                                                       
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret
---
apiVersion: v1
data:
  foo2: YmFyMg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret2

10:28:59 in ~/Downloads/kubeseal-test
➜ kubeseal --format yaml <mysecret.yaml >mysealedsecret.yaml

10:29:36 in ~/Downloads/kubeseal-test
➜ cat mysealedsecret.yaml 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBcOSwLF/cCWmAR7J3mZvFBJIYq7QIjBUQbymqHAhhUDwqpukiCRnA3Rr9iTOXUDOQLthjoujU9NLIM/5xpSFy2AjFRexA02B4ZoxqDFD2ZNxh1kFzedKEDRYgt855jaCwZZbqCnJc4Q4I9m0fWioj9+Ij3rFouVlu+QATpqyAZ7baiVa3wYp6s9YnDSsGwS0OI2URfB5wxZyEIF/vmw/TuZe6dN/qgPVQOK3wWN1+/j9dMYFPgUbTi9gcYr7SerYFCwi5dergNLagEb/zovMhQXymvvhFTeqk4AOZXXSpVbUNIIpdatLWntIXa1k7xNWIl+O1y0KHmLEmW8Ynv2GHbl0c04suJTAapMmWcVorlN1eRjmPaXogtPDTrbDMzs4SqFM6KAxhairwpjZEX8A7dIfWohGVb01aD4wjdzWd0Jgi5WL6LyCkhvV7YUGDfoJsV8Av1WF1snRJRh2ChoTGbHre2i6eZXAUUDDsLLnVRvEioCFMsKVe+pkXHwZhDhVrCmdswUB4mvNDolpEDZ/pj0ykz9M6WMTErs9VlNB1OHvWBr/B6AIDU/HTomJ4zd9siMhwN+zksLz88pfF8kcKlC/nHd+3xtsPsL8jZbppp8Bw1DwXu19FGOwpwDyGoFxkeB3OH5ECK9yuhHGdecoPoDLDco4An+NOgLI52Qp9fscTuezA4aw9AH7L71XQzqd6BB9A=
```

you can see only `mysecret` and `mysecret2` is truncated

### PR DESCRIPTION
**Pull request by theurichde**
**Description of the change**

Add Support for Multidoc YAML and JSON, as stated in #114 

**Benefits**

Users can have and manage multiple secrets in one file and encrypt those secrets in one run

**Possible drawbacks**

* This change does not apply to `--merge-into`
  * To use this with mutlidoc, we would need to specify a target secret. On the other hand, users can easily put their to-be-merged secret in a separate file 

* `Kind: List` resources are not considered / supported

**Applicable issues**

- fixes #114 

**Additional information**

I want to get your opinion on this approach and see if I am on the right track here.

### CODE REVIEW

**Comment by theurichde** [comment]
Hi there 👋🏻 

@alvneiayu @agarcia-oss @alemorcuq  

I would like to have your feedback on this draft before raising the actual PR. Any thoughts on this approach?
Sealing & validating single and multi-doc secrets (either JSON or YAML) is implemented.

**Comment by alvneiayu** [comment]
thanks for your contribution @theurichde. Let me take some time to test it and review it. Again, thanks a lot.

**Comment by alemorcuq** [comment]
Thanks for the PR, @theurichde. Could you please check the failed linter job? The feature looks good!

**Comment by theurichde** [comment]
Hey there @alvneiayu @alemorcuq 👋🏻 

Linting is fixed, should be green now.

I am wondering if we should put that feature somewhere (as a side note?) in the README? Maybe in the FAQ? 

For Example:

> Can I encrypt multiple secrets at once in one JSON / YAML file?
> -> You bet you can! Drop as many secrets as you like in one file. Make sure to separate them via `---`in YAML and as extra, single objects in JSON.

**Comment by alemorcuq** [comment]
> Hey there @alvneiayu @alemorcuq 👋🏻
> 
> Linting is fixed, should be green now.
> 
> I am wondering if we should put that feature somewhere (as a side note?) in the README? Maybe in the FAQ?

Yep, I think that would be great!

**Comment by theurichde** [comment]
@alemorcuq I added a small block for multi doc support in the FAQ

**Review by alemorcuq — APPROVED** [review]
This is a great job, @theurichde, thank you very much. This is ready to be merged but, due to some recent changes, a rebase is needed. Could you do that?

**Comment by theurichde** [comment]
@alemorcuq Thanks for reviewing! It's rebased and ready to rock 🤘🏻

**Review by alemorcuq — APPROVED** [review]

**Pull request merged**
