### PR TITLE
Initialize unsealErrorsTotal with "fetch" = 0

### PR DESCRIPTION
**Pull request by simon-anz**
Add part of the initialization from https://github.com/bitnami-labs/sealed-secrets/pull/463
See https://github.com/bitnami-labs/sealed-secrets/issues/543

### CODE REVIEW

**Comment by simon-anz** [comment]
@kskewes @mkmik

**Comment by kskewes** [comment]
LGTM per code incrementing error here: https://github.com/bitnami-labs/sealed-secrets/blob/62cfb264f53e9a378ef1b8df051ac4d8a2af5da0/cmd/controller/controller.go#L212

**Comment by simon-anz** [comment]
What is needed to progress this PR?

**Comment by alvneiayu** [comment]
hi @simon-anz 

Could you do a rebase to check that the test are passing, please?

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment]
Thanks a lot for the contribution but this solution, I think that it is incomplete. We are solving just this specific case but the problem is still present for the other cases.

Thanks again

**Pull request closed without merging**
