### PR TITLE
feat: add drop all capabilities

### LINKED ISSUE #1060: [feat] Add Drop ALL Capabilities
**Which component**:
This would affect controller (v0.19.2).

**Is your feature request related to a problem? Please describe.**
Currently it seems that 

```YAML
capabilities:
  drop: 
    - ALL
```

is missing from the container security context. If the container does not require those capabilities, would it be possible to drop them by default.

**Describe the solution you'd like**
The solution would have drop all capabilities by default in the controller if possible.

**Describe alternatives you've considered**
NONE

**Additional context**

### PR DESCRIPTION
**Pull request by JuanPabloSGU**
**Description of the change**

Added drop all capabilities to the container security context. 

**Benefits**

Capabilities permit privileged actions without giving full root access. All capabilities should be dropped from the container, with only those required added back.

**Possible drawbacks**
None

**Applicable issues**

- fixes #1060 

**Additional information**

### CODE REVIEW

**Comment by agarcia-oss** [comment]
@JuanPabloSGU thanks for the contribution! You'll need to include the [signed-off](https://github.com/bitnami-labs/sealed-secrets/blob/main/CONTRIBUTING.md#technical-requirements) in your commit to pass our CI process.  

Also, even though you've included changes in the chart default values, you'll need to create the template changes as well. 

The affected template is [deployment.yaml](https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/templates/deployment.yaml#L123)
Regards!

**Comment by JuanPabloSGU** [comment]
So I am not sure why the sign off isn't working. I am completely lost when it comes to updating the template file. However, I could be missing something obvious.

**Comment by agarcia-oss** [comment]
> So I am not sure why the sign off isn't working. I am completely lost when it comes to updating the template file. However, I could be missing something obvious.

Hi! you just need to follow the instructions on the DCO action [here](https://github.com/bitnami-labs/sealed-secrets/runs/10912468663). 

As for the template changes, I'm afraid the PR will not make sense without the chart changes. We can try to include the modifications ourselves, @alemorcuq ?

**Comment by alemorcuq** [comment]
Hi, @JuanPabloSGU. Sorry for the very late response.

Actually, the PR looks good as is. Could you please sign the DCO so that the CI can pass? The failed GitHub action will give you instructions on how to do so if you need them.

Thank you very much for the PR!

**Comment by JuanPabloSGU** [comment]
I believe that I completed messed up the PR and trying to fix the DCO is only making it worst. Let me know what I should do since I would like to contribute!

**Comment by alemorcuq** [comment]
> I believe that I completed messed up the PR and trying to fix the DCO is only making it worst. Let me know what I should do since I would like to contribute!

Perhaps it's easier if you create a new PR? When committing your changes, remember to do it using the `--signoff` flag to sign the DCO.

**Pull request closed without merging**
